### ISSUE TITLE
Translation issues: Inner/outer stairs and possible duplicates

### ISSUE THREAD

**Issue by srifqi** [mt-mods/gloopblocks#2]
Hello. I would like to report some translation issues.

### Stairs

The inner/outer stair node variants are not translatable.

I am not sure about the best way to fix this issue, but maybe we can look at MTG's `stairs` mod as an example: [[1]](https://github.com/minetest/minetest_game/blob/5.8.0/mods/stairs/init.lua#L443-L454) [[2]](https://github.com/minetest/minetest_game/blob/5.8.0/mods/stairs/init.lua#L931-L934)

```lua
-- Local function so we can apply translations
local function my_register_stair_and_slab(subname, recipeitem, groups, images,
		desc_stair, desc_slab, sounds, worldaligntex)
	stairs.register_stair(subname, recipeitem, groups, images, S(desc_stair),
		sounds, worldaligntex)
	stairs.register_stair_inner(subname, recipeitem, groups, images, "",
		sounds, worldaligntex, T("Inner " .. desc_stair))
	stairs.register_stair_outer(subname, recipeitem, groups, images, "",
		sounds, worldaligntex, T("Outer " .. desc_stair))
	stairs.register_slab(subname, recipeitem, groups, images, S(desc_slab),
		sounds, worldaligntex)
end

-- Dummy calls to S() to allow translation scripts to detect the strings.
-- To update this add this code to my_register_stair_and_slab:
-- for _,x in ipairs({"","Inner ","Outer "}) do print(("S(%q)"):format(x..desc_stair)) end
-- print(("S(%q)"):format(desc_slab))
```

### Possible duplicates

The string "Road Bed" and "Roadbed" refer to the same thing: _roadbed_. List of variants:
- (Mossy) Cobblestone Road Bed (as a regular node)
- (Mossy) Cobblestone Roadbed (as an input to `stairsplus`)
- (Mossy) Cobble Roadbed (as an input to `stairs`)

**Comment by wsor4035** [comment]
makes sense to convert all `Road Bed` instances to `Roadbed`. feel free to submit a PR for translatability and/or duplicates if you wish

**Comment by srifqi** [comment]
I will try.

I was going to attach some screenshots, but I accidentally clicked the Submit button. :)
